### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by studywolf** [ctn-archive/nengo_theano#11]
Could we just have a post with all the naming conventions we're using? For example, I have a class with two words in its name, the class name is FirstSecond, but is the file name first_second.py etc etc. In general it would probably be good to have a ready convention to refer people to, especially when first starting. Also because a lot of us are coming from whatever convention in whatever language we're used to coding in. So, Python convention, yes, but having specifics for the Python convention we're using here would be nice.

**Comment by tcstewar** [comment]
Here's the naming convention for Python, which I've been trying to stick to:

http://www.python.org/dev/peps/pep-0008/#naming-conventions

In the Nengo version, it's a bit more complicated, since the Java naming conventions are different, and aspects of that convention bleed through to Python in places.  But the Theano version (and the nef api in general) should be using the Python conventions.
