### ISSUE TITLE
Direct mode

### ISSUE THREAD

**Issue by studywolf** [ctn-archive/nengo_theano#7]
Not sure how high priority this would be, since we can do the direct mode stuff quickly in Nengo...

**Comment by jaberg** [comment]
Could be useful for testing?

Tests that various modes roughly match for various networks is a quick way
to test a lot of stuff at the same time for mathematical accuracy.

**Comment by tbekolay** [comment]
It'd be useful to do this, also, to future-proof the implementation, so that if we later want to introduce more modes (e.g. Express mode) the implementation can handle it.

**Comment by celiasmith** [comment]
Should definitely be high priority, as well as 'population mode' (which used to be 'express mode', but makes more sense to call it that).  This is perhaps the most common question I'm asked: can you simulate it without neurons and get the same results? Population mode will be a better approximation than direct mode, and both are useful for model design.  It's also important to be able to mix modes.

**Comment by bptripp** [comment]
Sorry, I think I missed part of this conversation, but are we talking here about a generic API for multiple target platforms?

If so, I'd like to suggest some kind of support for both minimal and more complete implementations. For example, conformance levels (e.g. basic, advanced), or one or two optional extensions, or something. One of the targets will be FPGAs, and it will be considerable extra work to do direct and population modes on them. (Same with NeuroGrid maybe?) So that might be something to leave out of the most stripped-down version. I just think we want a low entry-level bar.

Bryan

**Comment by studywolf** [comment]
I think this might not actually be too bad, I'm going to give just a basic direct mode a shot now.
